# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zymod/zhiyan_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zymod/zhiyan_rpc.proto',
  package='zhiyan_rpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16zymod/zhiyan_rpc.proto\x12\nzhiyan_rpc\"@\n\rZhiYanRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"/\n\x0eZhiYanResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2J\n\x06ZhiYan\x12@\n\x05zymod\x12\x19.zhiyan_rpc.ZhiYanRequest\x1a\x1a.zhiyan_rpc.ZhiYanResponse\"\x00\x62\x06proto3'
)




_ZHIYANREQUEST = _descriptor.Descriptor(
  name='ZhiYanRequest',
  full_name='zhiyan_rpc.ZhiYanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='zhiyan_rpc.ZhiYanRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='zhiyan_rpc.ZhiYanRequest.datetime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='zhiyan_rpc.ZhiYanRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=102,
)


_ZHIYANRESPONSE = _descriptor.Descriptor(
  name='ZhiYanResponse',
  full_name='zhiyan_rpc.ZhiYanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='zhiyan_rpc.ZhiYanResponse.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='zhiyan_rpc.ZhiYanResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['ZhiYanRequest'] = _ZHIYANREQUEST
DESCRIPTOR.message_types_by_name['ZhiYanResponse'] = _ZHIYANRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZhiYanRequest = _reflection.GeneratedProtocolMessageType('ZhiYanRequest', (_message.Message,), {
  'DESCRIPTOR' : _ZHIYANREQUEST,
  '__module__' : 'zymod.zhiyan_rpc_pb2'
  # @@protoc_insertion_point(class_scope:zhiyan_rpc.ZhiYanRequest)
  })
_sym_db.RegisterMessage(ZhiYanRequest)

ZhiYanResponse = _reflection.GeneratedProtocolMessageType('ZhiYanResponse', (_message.Message,), {
  'DESCRIPTOR' : _ZHIYANRESPONSE,
  '__module__' : 'zymod.zhiyan_rpc_pb2'
  # @@protoc_insertion_point(class_scope:zhiyan_rpc.ZhiYanResponse)
  })
_sym_db.RegisterMessage(ZhiYanResponse)



_ZHIYAN = _descriptor.ServiceDescriptor(
  name='ZhiYan',
  full_name='zhiyan_rpc.ZhiYan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=153,
  serialized_end=227,
  methods=[
  _descriptor.MethodDescriptor(
    name='zymod',
    full_name='zhiyan_rpc.ZhiYan.zymod',
    index=0,
    containing_service=None,
    input_type=_ZHIYANREQUEST,
    output_type=_ZHIYANRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ZHIYAN)

DESCRIPTOR.services_by_name['ZhiYan'] = _ZHIYAN

# @@protoc_insertion_point(module_scope)
